# Use new container infrastructure to enable caching
sudo: false

# Choose a lightweight base image; we provide our own build tools.
language: c

# GHC depends on GMP. You can add other dependencies here as well.
addons:
  apt:
    packages:
    - libgmp-dev

# The different configurations we want to test. You could also do things like
# change flags or use --stack-yaml to point to a different file.
env:
- LH_TRAVIS_STACK_ARGS="--stack-yaml stack-ghc82.yaml"
- LH_TRAVIS_STACK_ARGS="--stack-yaml stack-ghc84.yaml"

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
    - stack $LH_TRAVIS_STACK_ARGS setup --no-terminal
    - stack $LH_TRAVIS_STACK_ARGS build --only-snapshot --no-terminal

script:
    - stack $LH_TRAVIS_STACK_ARGS --no-terminal --install-ghc test --haddock --pedantic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
