#!/bin/bash

if [ -z "$1" -o "$1" == "--help" ]; then
    echo "USAGE: $0 [--heap] BENCHMARK_NAME"
    exit 1
fi

prof=time
if [ "$1" == "--heap" ]; then
    prof=heap
    shift
fi

stack build --executable-profiling --library-profiling --ghc-options=-fprof-auto

exe=$(stack exec -- which large-hashable-benchmark)

if [ "$prof" == "time" ]; then
    $exe $1 +RTS -p
else
    $exe $1 +RTS -hd
fi
