name: Haskell-CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
jobs:
  linux:
    name: Haskell-CI - Linux - ${{ matrix.compiler }}
    runs-on: ubuntu-latest
    timeout-minutes:
      60
    container:
      image: skogsbaer/ubuntu:20240502224354
    continue-on-error: false
    strategy:
      matrix:
        include:
          - compiler: ghc-9.10
          - compiler: ghc-9.8
          - compiler: ghc-9.6
      fail-fast: false
    steps:
      - name: Set PATH and environment variables
        run: |
          echo "LH_TEST_STACK_YAML=$GITHUB_WORKSPACE/stack-${{ matrix.compiler }}.yaml" >> "$GITHUB_ENV"
      - name: checkout
        uses: actions/checkout@v3
      - name: Permissions bug workaround
        run: "chown -R $(id -un):$(id -gn) ~"
      - name: Compute cache key
        run: |
          lsb_release -a > cache-key 2> /dev/null
          cat large-hashable.cabal $(which stack) "$LH_TEST_STACK_YAML" scripts/ci-check >> cache-key
          LH_CACHE_KEY="$(md5sum cache-key | cut -c 1-32)"
          echo "LH_CACHE_KEY=$LH_CACHE_KEY" >> "$GITHUB_ENV"
          echo "LH_CACHE_KEY=$LH_CACHE_KEY"
      - name: Cache stack dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.stack
            ~/.LH-stack-work
          key: ${{ runner.OS }}-stack-cache-v1-${{ matrix.compiler }}-${{ env.LH_CACHE_KEY }}
          restore-keys: |
            ${{ runner.OS }}-stack-cache-v1-${{ matrix.compiler }}
      - name: test
        run: scripts/ci-check
